2023-07-24 15:20:54,538 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1 running 'init-local' at Mon, 24 Jul 2023 15:20:54 +0000. Up 76.95 seconds.
2023-07-24 15:20:54,538 - main.py[DEBUG]: No kernel command line url found.
2023-07-24 15:20:54,538 - main.py[DEBUG]: Closing stdin.
2023-07-24 15:20:54,542 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2023-07-24 15:20:54,542 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 107:4
2023-07-24 15:20:54,542 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 4 bytes
2023-07-24 15:20:54,543 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2023-07-24 15:20:54,543 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2023-07-24 15:20:54,543 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2023-07-24 15:20:54,543 - stages.py[DEBUG]: no cache found
2023-07-24 15:20:54,543 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2023-07-24 15:20:54,543 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2023-07-24 15:20:54,552 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-07-24 15:20:54,553 - __init__.py[DEBUG]: Looking for data source in: ['NoCloud', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2023-07-24 15:20:54,558 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceNoCloud']
2023-07-24 15:20:54,559 - handlers.py[DEBUG]: start: init-local/search-NoCloud: searching for local data from DataSourceNoCloud
2023-07-24 15:20:54,559 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'>
2023-07-24 15:20:54,559 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2023-07-24 15:20:54,559 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2023-07-24 15:20:54,559 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/user-data (quiet=False)
2023-07-24 15:20:54,559 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/seed/nocloud/user-data
2023-07-24 15:20:54,559 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
2023-07-24 15:20:54,559 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/seed/nocloud/meta-data
2023-07-24 15:20:54,559 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/vendor-data (quiet=False)
2023-07-24 15:20:54,559 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
2023-07-24 15:20:54,560 - DataSourceNoCloud.py[DEBUG]: Using seeded data from /var/lib/cloud/seed/nocloud
2023-07-24 15:20:54,560 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,560 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-07-24 15:20:54,560 - subp.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2023-07-24 15:20:54,618 - subp.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2023-07-24 15:20:54,629 - subp.py[DEBUG]: Running command ['blkid', '-tLABEL=CIDATA', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2023-07-24 15:20:54,643 - subp.py[DEBUG]: Running command ['blkid', '-tLABEL=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2023-07-24 15:20:54,671 - subp.py[DEBUG]: Running command ['blkid', '-tLABEL_FATBOOT=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
2023-07-24 15:20:54,684 - util.py[DEBUG]: Reading from /etc/hosts (quiet=False)
2023-07-24 15:20:54,685 - util.py[DEBUG]: Read 250 bytes from /etc/hosts
2023-07-24 15:20:54,686 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-nocloud - wb: [644] 8 bytes
2023-07-24 15:20:54,687 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-nocloud'
2023-07-24 15:20:54,687 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp63ajncgb) - w: [600] 4431 bytes/chars
2023-07-24 15:20:54,688 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpsuk02e_g) - w: [644] 1452 bytes/chars
2023-07-24 15:20:54,688 - handlers.py[DEBUG]: finish: init-local/search-NoCloud: SUCCESS: found local data from DataSourceNoCloud
2023-07-24 15:20:54,688 - stages.py[INFO]: Loaded datasource DataSourceNoCloud - DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud][dsmode=net]
2023-07-24 15:20:54,688 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-07-24 15:20:54,689 - util.py[DEBUG]: Read 3487 bytes from /etc/cloud/cloud.cfg
2023-07-24 15:20:54,689 - util.py[DEBUG]: Attempting to load yaml from string of length 3487 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,706 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2023-07-24 15:20:54,707 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2023-07-24 15:20:54,707 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,710 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/06_quiet.cfg (quiet=False)
2023-07-24 15:20:54,711 - util.py[DEBUG]: Read 112 bytes from /etc/cloud/cloud.cfg.d/06_quiet.cfg
2023-07-24 15:20:54,711 - util.py[DEBUG]: Attempting to load yaml from string of length 112 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,712 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-07-24 15:20:54,712 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-07-24 15:20:54,712 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,718 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-07-24 15:20:54,718 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2023-07-24 15:20:54,718 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,719 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,720 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-07-24 15:20:54,722 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2023-07-24 15:20:54,722 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/nocloud'
2023-07-24 15:20:54,724 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/nocloud/datasource (quiet=False)
2023-07-24 15:20:54,725 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/datasource - wb: [644] 84 bytes
2023-07-24 15:20:54,725 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 84 bytes
2023-07-24 15:20:54,726 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2023-07-24 15:20:54,726 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2023-07-24 15:20:54,727 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 8 bytes
2023-07-24 15:20:54,728 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 8 bytes
2023-07-24 15:20:54,728 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2023-07-24 15:20:54,729 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 5358 bytes
2023-07-24 15:20:54,730 - main.py[DEBUG]: [local] init will now be targeting instance id: nocloud. new=True
2023-07-24 15:20:54,730 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-07-24 15:20:54,730 - util.py[DEBUG]: Read 3487 bytes from /etc/cloud/cloud.cfg
2023-07-24 15:20:54,731 - util.py[DEBUG]: Attempting to load yaml from string of length 3487 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,747 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2023-07-24 15:20:54,747 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2023-07-24 15:20:54,747 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,750 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/06_quiet.cfg (quiet=False)
2023-07-24 15:20:54,750 - util.py[DEBUG]: Read 112 bytes from /etc/cloud/cloud.cfg.d/06_quiet.cfg
2023-07-24 15:20:54,750 - util.py[DEBUG]: Attempting to load yaml from string of length 112 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,751 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-07-24 15:20:54,751 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-07-24 15:20:54,751 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,757 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-07-24 15:20:54,757 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2023-07-24 15:20:54,757 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,758 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:54,758 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-07-24 15:20:54,759 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-07-24 15:20:54,761 - util.py[DEBUG]: Reading from /sys/class/net/ens33/address (quiet=False)
2023-07-24 15:20:54,761 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens33/address
2023-07-24 15:20:54,761 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-07-24 15:20:54,761 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-07-24 15:20:54,761 - util.py[DEBUG]: Reading from /sys/class/net/ens33/address (quiet=False)
2023-07-24 15:20:54,761 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens33/address
2023-07-24 15:20:54,762 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-07-24 15:20:54,762 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-07-24 15:20:54,762 - util.py[DEBUG]: Reading from /sys/class/net/ens33/addr_assign_type (quiet=False)
2023-07-24 15:20:54,762 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens33/addr_assign_type
2023-07-24 15:20:54,762 - util.py[DEBUG]: Reading from /sys/class/net/ens33/uevent (quiet=False)
2023-07-24 15:20:54,762 - util.py[DEBUG]: Read 26 bytes from /sys/class/net/ens33/uevent
2023-07-24 15:20:54,762 - util.py[DEBUG]: Reading from /sys/class/net/ens33/address (quiet=False)
2023-07-24 15:20:54,763 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens33/address
2023-07-24 15:20:54,765 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2023-07-24 15:20:54,765 - util.py[DEBUG]: Reading from /sys/class/net/ens33/device/device (quiet=False)
2023-07-24 15:20:54,765 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens33/device/device
2023-07-24 15:20:54,765 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2023-07-24 15:20:54,765 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2023-07-24 15:20:54,765 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2023-07-24 15:20:54,765 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2023-07-24 15:20:54,765 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-07-24 15:20:54,765 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-07-24 15:20:54,765 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2023-07-24 15:20:54,765 - util.py[DEBUG]: Reading from /sys/class/net/ens33/type (quiet=False)
2023-07-24 15:20:54,766 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens33/type
2023-07-24 15:20:54,766 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2023-07-24 15:20:54,766 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2023-07-24 15:20:54,766 - networking.py[DEBUG]: net: all expected physical devices present
2023-07-24 15:20:54,766 - stages.py[DEBUG]: applying net config names for {'version': 2, 'ethernets': {'zz-all-en': {'match': {'name': 'en*'}, 'dhcp4': True}, 'zz-all-eth': {'match': {'name': 'eth*'}, 'dhcp4': True}}}
2023-07-24 15:20:54,766 - __init__.py[DEBUG]: no interfaces to rename
2023-07-24 15:20:54,766 - stages.py[INFO]: Applying network configuration from system_cfg bringup=False: {'version': 2, 'ethernets': {'zz-all-en': {'match': {'name': 'en*'}, 'dhcp4': True}, 'zz-all-eth': {'match': {'name': 'eth*'}, 'dhcp4': True}}}
2023-07-24 15:20:54,766 - util.py[DEBUG]: Writing to /run/cloud-init/sem/apply_network_config.once - wb: [644] 24 bytes
2023-07-24 15:20:54,773 - __init__.py[DEBUG]: Selected renderer 'netplan' from priority list: None
2023-07-24 15:20:54,773 - network_state.py[DEBUG]: Passthrough netplan v2 config
2023-07-24 15:20:54,775 - netplan.py[DEBUG]: V2 to V2 passthrough
2023-07-24 15:20:54,776 - util.py[DEBUG]: Writing to /etc/netplan/50-cloud-init.yaml - wb: [644] 529 bytes
2023-07-24 15:20:54,777 - subp.py[DEBUG]: Running command ['netplan', 'generate'] with allowed return codes [0] (shell=False, capture=True)
2023-07-24 15:20:55,363 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/ens33'] with allowed return codes [0] (shell=False, capture=True)
2023-07-24 15:20:55,369 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo'] with allowed return codes [0] (shell=False, capture=True)
2023-07-24 15:20:55,373 - __init__.py[DEBUG]: Not bringing up newly configured network interfaces
2023-07-24 15:20:55,373 - main.py[DEBUG]: [local] Exiting. datasource DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud][dsmode=net] not in local mode.
2023-07-24 15:20:55,374 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp7o_obd6j) - w: [644] 537 bytes/chars
2023-07-24 15:20:55,374 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-07-24 15:20:55,374 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2023-07-24 15:20:55,374 - util.py[DEBUG]: cloud-init mode 'init' took 0.906 seconds (0.91)
2023-07-24 15:20:55,374 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2023-07-24 15:20:56,232 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1 running 'init' at Mon, 24 Jul 2023 15:20:56 +0000. Up 78.65 seconds.
2023-07-24 15:20:56,232 - main.py[DEBUG]: No kernel command line url found.
2023-07-24 15:20:56,232 - main.py[DEBUG]: Closing stdin.
2023-07-24 15:20:56,234 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2023-07-24 15:20:56,234 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 107:4
2023-07-24 15:20:56,238 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2023-07-24 15:20:56,903 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2023-07-24 15:20:57,088 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2023-07-24 15:20:57,090 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2023-07-24 15:20:57,091 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2023-07-24 15:20:57,091 - util.py[DEBUG]: Read 5358 bytes from /var/lib/cloud/instance/obj.pkl
2023-07-24 15:20:57,093 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)
2023-07-24 15:20:57,093 - util.py[DEBUG]: Read 8 bytes from /run/cloud-init/.instance-id
2023-07-24 15:20:57,093 - stages.py[DEBUG]: restored from cache with run check: DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud][dsmode=net]
2023-07-24 15:20:57,094 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: restored from cache with run check: DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud][dsmode=net]
2023-07-24 15:20:57,094 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-07-24 15:20:57,094 - util.py[DEBUG]: Read 3487 bytes from /etc/cloud/cloud.cfg
2023-07-24 15:20:57,094 - util.py[DEBUG]: Attempting to load yaml from string of length 3487 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,106 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2023-07-24 15:20:57,106 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2023-07-24 15:20:57,106 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,108 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/06_quiet.cfg (quiet=False)
2023-07-24 15:20:57,108 - util.py[DEBUG]: Read 112 bytes from /etc/cloud/cloud.cfg.d/06_quiet.cfg
2023-07-24 15:20:57,108 - util.py[DEBUG]: Attempting to load yaml from string of length 112 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,109 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-07-24 15:20:57,109 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-07-24 15:20:57,109 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,113 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-07-24 15:20:57,113 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2023-07-24 15:20:57,113 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,113 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,113 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-07-24 15:20:57,114 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2023-07-24 15:20:57,114 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/nocloud'
2023-07-24 15:20:57,115 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/nocloud/datasource (quiet=False)
2023-07-24 15:20:57,115 - util.py[DEBUG]: Read 84 bytes from /var/lib/cloud/instances/nocloud/datasource
2023-07-24 15:20:57,115 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/datasource - wb: [644] 84 bytes
2023-07-24 15:20:57,115 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 84 bytes
2023-07-24 15:20:57,116 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2023-07-24 15:20:57,116 - util.py[DEBUG]: Read 8 bytes from /var/lib/cloud/data/instance-id
2023-07-24 15:20:57,116 - stages.py[DEBUG]: previous iid found to be nocloud
2023-07-24 15:20:57,116 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 8 bytes
2023-07-24 15:20:57,116 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 8 bytes
2023-07-24 15:20:57,116 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 8 bytes
2023-07-24 15:20:57,117 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 5370 bytes
2023-07-24 15:20:57,117 - main.py[DEBUG]: [net] init will now be targeting instance id: nocloud. new=False
2023-07-24 15:20:57,118 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-07-24 15:20:57,118 - util.py[DEBUG]: Read 3487 bytes from /etc/cloud/cloud.cfg
2023-07-24 15:20:57,118 - util.py[DEBUG]: Attempting to load yaml from string of length 3487 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,128 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2023-07-24 15:20:57,128 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2023-07-24 15:20:57,128 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,130 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/06_quiet.cfg (quiet=False)
2023-07-24 15:20:57,130 - util.py[DEBUG]: Read 112 bytes from /etc/cloud/cloud.cfg.d/06_quiet.cfg
2023-07-24 15:20:57,130 - util.py[DEBUG]: Attempting to load yaml from string of length 112 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,130 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-07-24 15:20:57,130 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-07-24 15:20:57,130 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,134 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-07-24 15:20:57,134 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2023-07-24 15:20:57,134 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,134 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,134 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-07-24 15:20:57,135 - util.py[DEBUG]: Reading from /sys/class/net/ens33/address (quiet=False)
2023-07-24 15:20:57,135 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens33/address
2023-07-24 15:20:57,135 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-07-24 15:20:57,135 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-07-24 15:20:57,136 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2023-07-24 15:20:57,136 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=boot-legacy
2023-07-24 15:20:57,136 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update allowed
2023-07-24 15:20:57,136 - stages.py[DEBUG]: applying net config names for {'version': 2, 'ethernets': {'zz-all-en': {'match': {'name': 'en*'}, 'dhcp4': True}, 'zz-all-eth': {'match': {'name': 'eth*'}, 'dhcp4': True}}}
2023-07-24 15:20:57,137 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-07-24 15:20:57,137 - __init__.py[DEBUG]: no interfaces to rename
2023-07-24 15:20:57,137 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2023-07-24 15:20:57,137 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2023-07-24 15:20:57,137 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/user-data.txt - wb: [600] 0 bytes
2023-07-24 15:20:57,144 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/user-data.txt.i - wb: [600] 308 bytes
2023-07-24 15:20:57,145 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/vendor-data.txt - wb: [600] 0 bytes
2023-07-24 15:20:57,146 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/vendor-data.txt.i - wb: [600] 308 bytes
2023-07-24 15:20:57,146 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/vendor-data2.txt - wb: [600] 0 bytes
2023-07-24 15:20:57,147 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/vendor-data2.txt.i - wb: [600] 308 bytes
2023-07-24 15:20:57,148 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/sem/consume_data - wb: [644] 24 bytes
2023-07-24 15:20:57,148 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/nocloud/sem/consume_data'>)
2023-07-24 15:20:57,148 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2023-07-24 15:20:57,148 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2023-07-24 15:20:57,149 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2023-07-24 15:20:57,149 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2023-07-24 15:20:57,149 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2023-07-24 15:20:57,149 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2023-07-24 15:20:57,149 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2023-07-24 15:20:57,149 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2023-07-24 15:20:57,149 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2023-07-24 15:20:57,149 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2023-07-24 15:20:57,149 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2023-07-24 15:20:57,149 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2023-07-24 15:20:57,149 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2023-07-24 15:20:57,149 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2023-07-24 15:20:57,149 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2023-07-24 15:20:57,149 - __init__.py[DEBUG]: {'MIME-Version': '1.0', 'Content-Type': 'text/x-not-multipart', 'Content-Disposition': 'attachment; filename="part-001"'}
2023-07-24 15:20:57,149 - __init__.py[DEBUG]: Empty payload of type text/x-not-multipart
2023-07-24 15:20:57,149 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2023-07-24 15:20:57,149 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/cloud-config.txt - wb: [600] 0 bytes
2023-07-24 15:20:57,150 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2023-07-24 15:20:57,150 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2023-07-24 15:20:57,150 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2023-07-24 15:20:57,150 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2023-07-24 15:20:57,150 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2023-07-24 15:20:57,150 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2023-07-24 15:20:57,150 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2023-07-24 15:20:57,150 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2023-07-24 15:20:57,150 - stages.py[DEBUG]: no vendordata from datasource
2023-07-24 15:20:57,150 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2023-07-24 15:20:57,150 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2023-07-24 15:20:57,150 - stages.py[DEBUG]: no vendordata2 from datasource
2023-07-24 15:20:57,150 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2023-07-24 15:20:57,151 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-07-24 15:20:57,151 - util.py[DEBUG]: Read 3487 bytes from /etc/cloud/cloud.cfg
2023-07-24 15:20:57,151 - util.py[DEBUG]: Attempting to load yaml from string of length 3487 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,160 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2023-07-24 15:20:57,160 - util.py[DEBUG]: Read 314 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2023-07-24 15:20:57,161 - util.py[DEBUG]: Attempting to load yaml from string of length 314 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,162 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/06_quiet.cfg (quiet=False)
2023-07-24 15:20:57,162 - util.py[DEBUG]: Read 112 bytes from /etc/cloud/cloud.cfg.d/06_quiet.cfg
2023-07-24 15:20:57,162 - util.py[DEBUG]: Attempting to load yaml from string of length 112 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,163 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-07-24 15:20:57,163 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-07-24 15:20:57,164 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,167 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-07-24 15:20:57,167 - util.py[DEBUG]: Read 35 bytes from /run/cloud-init/cloud.cfg
2023-07-24 15:20:57,167 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,167 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,167 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-07-24 15:20:57,168 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2023-07-24 15:20:57,168 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2023-07-24 15:20:57,168 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,168 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-07-24 15:20:57,168 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:20:57,169 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:20:57,179 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2023-07-24 15:20:57,179 - util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
2023-07-24 15:20:57,179 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-07-24 15:20:57,179 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-07-24 15:20:57,181 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2023-07-24 15:20:57,182 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 7460 bytes
2023-07-24 15:20:57,182 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2023-07-24 15:20:57,182 - main.py[DEBUG]: no di_report found in config.
2023-07-24 15:20:57,189 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:20:57,189 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:20:57,196 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:20:57,196 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:20:57,198 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:20:57,198 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:20:57,200 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:20:57,200 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:20:57,207 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:20:57,207 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:20:57,210 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:20:57,210 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:20:57,212 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-07-24 15:20:57,212 - modules.py[INFO]: Skipping modules 'bootcmd,write-files,ca-certs,rsyslog' because no applicable config is provided.
2023-07-24 15:20:57,213 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2023-07-24 15:20:57,213 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2023-07-24 15:20:57,213 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/sem/config_users_groups - wb: [644] 25 bytes
2023-07-24 15:20:57,213 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/nocloud/sem/config_users_groups'>)
2023-07-24 15:20:57,214 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2023-07-24 15:20:57,215 - util.py[DEBUG]: Read 392 bytes from /etc/os-release
2023-07-24 15:20:57,215 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2023-07-24 15:20:57,216 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2023-07-24 15:20:57,217 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2023-07-24 15:20:57,218 - util.py[DEBUG]: Read 392 bytes from /etc/os-release
2023-07-24 15:20:57,218 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2023-07-24 15:20:57,218 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2023-07-24 15:20:57,219 - subp.py[DEBUG]: Running command ['groupadd', 'netdev'] with allowed return codes [0] (shell=False, capture=True)
2023-07-24 15:20:57,226 - __init__.py[INFO]: Created new group netdev
2023-07-24 15:20:57,226 - __init__.py[DEBUG]: created group 'netdev' for user 'installer'
2023-07-24 15:20:57,226 - __init__.py[DEBUG]: Adding user installer
2023-07-24 15:20:57,226 - subp.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'installer', '--comment', 'Ubuntu', '--groups', 'adm,audio,cdrom,dialout,dip,floppy,lxd,netdev,plugdev,sudo,video', '--shell', '/usr/bin/subiquity-shell', '-m']
2023-07-24 15:20:57,239 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2023-07-24 15:20:57,243 - util.py[DEBUG]: Read 1800 bytes from /etc/sudoers
2023-07-24 15:20:57,244 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 139 bytes
2023-07-24 15:20:57,244 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2023-07-24 15:20:57,245 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2023-07-24 15:20:57,245 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2023-07-24 15:20:57,245 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/sem/config_ssh - wb: [644] 24 bytes
2023-07-24 15:20:57,245 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/nocloud/sem/config_ssh'>)
2023-07-24 15:20:57,248 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)
2023-07-24 15:20:58,283 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2023-07-24 15:20:58,283 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=True)
2023-07-24 15:20:58,374 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2023-07-24 15:20:58,375 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2023-07-24 15:20:58,385 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2023-07-24 15:20:58,385 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2023-07-24 15:20:58,392 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2023-07-24 15:20:58,392 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2023-07-24 15:20:58,392 - util.py[DEBUG]: Read 100 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2023-07-24 15:20:58,393 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2023-07-24 15:20:58,393 - util.py[DEBUG]: Read 180 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2023-07-24 15:20:58,393 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_rsa_key.pub (quiet=False)
2023-07-24 15:20:58,393 - util.py[DEBUG]: Read 572 bytes from /etc/ssh/ssh_host_rsa_key.pub
2023-07-24 15:20:58,394 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2023-07-24 15:20:58,394 - util.py[DEBUG]: Read 3455 bytes from /etc/ssh/sshd_config
2023-07-24 15:20:58,395 - util.py[DEBUG]: Changing the ownership of /home/installer/.ssh to 1000:1001
2023-07-24 15:20:58,395 - util.py[DEBUG]: Writing to /home/installer/.ssh/authorized_keys - wb: [600] 0 bytes
2023-07-24 15:20:58,395 - util.py[DEBUG]: Changing the ownership of /home/installer/.ssh/authorized_keys to 1000:1001
2023-07-24 15:20:58,395 - util.py[DEBUG]: Reading from /home/installer/.ssh/authorized_keys (quiet=False)
2023-07-24 15:20:58,395 - util.py[DEBUG]: Read 0 bytes from /home/installer/.ssh/authorized_keys
2023-07-24 15:20:58,395 - util.py[DEBUG]: Writing to /home/installer/.ssh/authorized_keys - wb: [600] 0 bytes
2023-07-24 15:20:58,396 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2023-07-24 15:20:58,396 - util.py[DEBUG]: Read 3455 bytes from /etc/ssh/sshd_config
2023-07-24 15:20:58,397 - util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
2023-07-24 15:20:58,397 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2023-07-24 15:20:58,398 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2023-07-24 15:20:58,398 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2023-07-24 15:20:58,398 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2023-07-24 15:20:58,398 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2023-07-24 15:20:58,398 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2023-07-24 15:20:58,398 - main.py[DEBUG]: Ran 2 modules with 0 failures
2023-07-24 15:20:58,399 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp7lzmzwir) - w: [644] 565 bytes/chars
2023-07-24 15:20:58,399 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-07-24 15:20:58,399 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2023-07-24 15:20:58,399 - util.py[DEBUG]: cloud-init mode 'init' took 2.214 seconds (2.21)
2023-07-24 15:20:58,399 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2023-07-24 15:21:12,179 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1 running 'modules:config' at Mon, 24 Jul 2023 15:21:12 +0000. Up 94.56 seconds.
2023-07-24 15:21:12,187 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:21:12,188 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:21:12,193 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:21:12,194 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:21:12,198 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:21:12,198 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:21:12,206 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:21:12,206 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:21:12,209 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:21:12,209 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:21:12,211 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-07-24 15:21:12,212 - modules.py[INFO]: Skipping modules 'timezone,disable-ec2-metadata,runcmd' because no applicable config is provided.
2023-07-24 15:21:12,212 - modules.py[DEBUG]: Running module ssh-import-id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequency once-per-instance
2023-07-24 15:21:12,212 - handlers.py[DEBUG]: start: modules-config/config-ssh-import-id: running config-ssh-import-id with frequency once-per-instance
2023-07-24 15:21:12,212 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/sem/config_ssh_import_id - wb: [644] 24 bytes
2023-07-24 15:21:12,213 - helpers.py[DEBUG]: Running config-ssh-import-id using lock (<FileLock using file '/var/lib/cloud/instances/nocloud/sem/config_ssh_import_id'>)
2023-07-24 15:21:12,213 - cc_ssh_import_id.py[DEBUG]: Skipping module named ssh-import-id, no 'ssh_import_id' directives found.
2023-07-24 15:21:12,213 - handlers.py[DEBUG]: finish: modules-config/config-ssh-import-id: SUCCESS: config-ssh-import-id ran successfully
2023-07-24 15:21:12,213 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2023-07-24 15:21:12,213 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2023-07-24 15:21:12,213 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/sem/config_set_passwords - wb: [644] 24 bytes
2023-07-24 15:21:12,214 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/nocloud/sem/config_set_passwords'>)
2023-07-24 15:21:12,214 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'ssh'] with allowed return codes [0] (shell=False, capture=True)
2023-07-24 15:21:12,232 - cc_set_passwords.py[DEBUG]: Writing config 'ssh_pwauth: True'. SSH service 'ssh' will not be restarted because it is stopped.
2023-07-24 15:21:12,234 - util.py[DEBUG]: Writing to /etc/ssh/sshd_config.d/50-cloud-init.conf - ab: [600] 0 bytes
2023-07-24 15:21:12,234 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config.d/50-cloud-init.conf (quiet=False)
2023-07-24 15:21:12,235 - util.py[DEBUG]: Read 0 bytes from /etc/ssh/sshd_config.d/50-cloud-init.conf
2023-07-24 15:21:12,235 - ssh_util.py[DEBUG]: line 1: option PasswordAuthentication added with yes
2023-07-24 15:21:12,235 - util.py[DEBUG]: Writing to /etc/ssh/sshd_config.d/50-cloud-init.conf - wb: [600] 27 bytes
2023-07-24 15:21:12,235 - cc_set_passwords.py[DEBUG]: Not restarting SSH service: service is stopped.
2023-07-24 15:21:12,235 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2023-07-24 15:21:12,235 - main.py[DEBUG]: Ran 2 modules with 0 failures
2023-07-24 15:21:12,236 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpjozgstbm) - w: [644] 593 bytes/chars
2023-07-24 15:21:12,236 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-07-24 15:21:12,236 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2023-07-24 15:21:12,236 - util.py[DEBUG]: cloud-init mode 'modules' took 0.146 seconds (0.15)
2023-07-24 15:21:12,236 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2023-07-24 15:21:14,826 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1 running 'modules:final' at Mon, 24 Jul 2023 15:21:14 +0000. Up 97.22 seconds.
2023-07-24 15:21:14,828 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:21:14,828 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:21:14,830 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:21:14,830 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:21:14,832 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:21:14,832 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:21:14,838 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:21:14,838 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:21:14,840 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:21:14,840 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:21:14,842 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-07-24 15:21:14,842 - util.py[DEBUG]: Read 114749 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-07-24 15:21:14,843 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-07-24 15:21:14,844 - modules.py[INFO]: Skipping modules 'phone-home' because no applicable config is provided.
2023-07-24 15:21:14,844 - modules.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2023-07-24 15:21:14,844 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
2023-07-24 15:21:14,845 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 25 bytes
2023-07-24 15:21:14,845 - helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2023-07-24 15:21:14,845 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
2023-07-24 15:21:14,845 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2023-07-24 15:21:14,845 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
2023-07-24 15:21:14,845 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/sem/config_scripts_user - wb: [644] 25 bytes
2023-07-24 15:21:14,846 - helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/nocloud/sem/config_scripts_user'>)
2023-07-24 15:21:14,846 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2023-07-24 15:21:14,846 - modules.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2023-07-24 15:21:14,846 - handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
2023-07-24 15:21:14,846 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/sem/config_ssh_authkey_fingerprints - wb: [644] 24 bytes
2023-07-24 15:21:14,846 - helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/nocloud/sem/config_ssh_authkey_fingerprints'>)
2023-07-24 15:21:14,846 - cc_ssh_authkey_fingerprints.py[DEBUG]: Skipping module named ssh-authkey-fingerprints, logging of SSH fingerprints disabled
2023-07-24 15:21:14,847 - handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
2023-07-24 15:21:14,847 - modules.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2023-07-24 15:21:14,847 - handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
2023-07-24 15:21:14,847 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/nocloud/sem/config_keys_to_console - wb: [644] 24 bytes
2023-07-24 15:21:14,847 - helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/nocloud/sem/config_keys_to_console'>)
2023-07-24 15:21:14,847 - cc_keys_to_console.py[DEBUG]: Skipping module named keys-to-console, logging of SSH host keys disabled
2023-07-24 15:21:14,847 - handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
2023-07-24 15:21:14,847 - modules.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2023-07-24 15:21:14,847 - handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
2023-07-24 15:21:14,847 - helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7f312b8d6e60>)
2023-07-24 15:21:14,848 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-07-24 15:21:14,848 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2023-07-24 15:21:14,857 - util.py[DEBUG]: Cloud-init v. 22.3.4-0ubuntu1 finished at Mon, 24 Jul 2023 15:21:14 +0000. Datasource DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud][dsmode=net].  Up 97.28 seconds
2023-07-24 15:21:14,857 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 61 bytes
2023-07-24 15:21:14,858 - handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
2023-07-24 15:21:14,858 - main.py[DEBUG]: Ran 5 modules with 0 failures
2023-07-24 15:21:14,858 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp8tst62sv) - w: [644] 621 bytes/chars
2023-07-24 15:21:14,858 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpm_8o1eab) - w: [644] 115 bytes/chars
2023-07-24 15:21:14,858 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2023-07-24 15:21:14,858 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-07-24 15:21:14,858 - util.py[DEBUG]: Read 13 bytes from /proc/uptime
2023-07-24 15:21:14,858 - util.py[DEBUG]: cloud-init mode 'modules' took 0.097 seconds (0.10)
2023-07-24 15:21:14,859 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
